services:

  # ── Base de Datos MySQL ──────────────────────────────────────────────────
  mysql_db:
    image: mysql:8.0
    container_name: callsos_bd
    restart: always
    env_file:
      - .env  # Docker buscará las variables aquí
    environment:
      # Estas variables se llenarán con los valores del archivo .env
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Mapeo de la carpeta database en la raíz para ejecutar los .sql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - red-callsos
    
    #Original
    #healthcheck:
    #  test: ["CMD", "mysqladmin", "ping", "-h", "localhost",
    #         "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5
    #  start_period: 30s
    
    #Prueba
    healthcheck:
      test:
        - CMD-SHELL
        - mysqladmin ping -uroot -p${MYSQL_ROOT_PASSWORD} --silent || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 90s


  # ── Backend Spring Boot ──────────────────────────────────────────────────
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: callsos-backend
    restart: always
    env_file:
      - .env
    
    volumes:
      - ./firebase/serviceAccountKey.json:/app/firebase/serviceAccountKey.json:ro
    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

      - FIREBASE_CREDENTIALS_PATH=${FIREBASE_CREDENTIALS_PATH}

    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - red-callsos

  # ── Frontend Flutter ─────────────────────────────────────────────────────
  frontend:
    build:
      context: ../callsos-frontend
      dockerfile: Dockerfile
    container_name: callsos-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - red-callsos

volumes:
  mysql_data:

networks:
  red-callsos:
    driver: bridge