services:

  mysql:
    image: mysql:8
    container_name: callsos-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: callsos
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  backend:
    build: .
    container_name: callsos-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/callsos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root