-- Tabla de CAIS
-- NOTA LA TABLA NO NECESARIAMENTE SE LLAMRÁ ASI, DEPENDE DE LO PLANTEADO EN LAS ENTIDADES DE DOMINIO
CREATE TABLE cais_cartagena (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    latitud DECIMAL(10,8) NOT NULL,
    longitud DECIMAL(11,8) NOT NULL
);